[package]
name = "mergify"
version = "0.1.0"
authors = ["einzigartigerName"]
edition = "2018"

[dependencies]
rspotify = "0.6.0"
rand = "0.7.0"

[dependencies.regex]
version = "1.3.0"
default-features = false
features = ["std"]

[profile.release]
lto = true